# Generated by Django 3.0 on 2024-12-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=50, null=True)),
                ('Company_address', models.CharField(max_length=50, null=True)),
                ('Company_GST', models.CharField(max_length=50, null=True)),
                ('Company_number', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_code', models.CharField(max_length=50, null=True)),
                ('Item_name', models.CharField(max_length=50, null=True)),
                ('Item_GST', models.CharField(max_length=50, null=True)),
                ('Item_price', models.CharField(max_length=50, null=True)),
                ('Category', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Table_name', models.CharField(max_length=50, null=True)),
                ('Category', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100, null=True)),
                ('bill_no', models.CharField(max_length=100, null=True)),
                ('bill_date', models.DateField()),
                ('bill_time', models.TimeField(null=True)),
                ('item_code', models.CharField(max_length=100, null=True)),
                ('item_name', models.CharField(max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('gst', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('qty', models.IntegerField()),
                ('tax_amt', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_gst', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('item_cat', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100, null=True)),
                ('bill_no', models.CharField(max_length=100, null=True)),
                ('bill_date', models.DateField()),
                ('bill_time', models.TimeField(null=True)),
                ('item_code', models.CharField(max_length=100, null=True)),
                ('item_name', models.CharField(max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('gst', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('qty', models.IntegerField()),
                ('tax_amt', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_gst', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('item_cat', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pracel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=100, null=True)),
                ('bill_date', models.DateField()),
                ('bill_time', models.TimeField(null=True)),
                ('item_code', models.CharField(max_length=100, null=True)),
                ('item_name', models.CharField(max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('gst', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('qty', models.IntegerField()),
                ('tax_amt', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_gst', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('pracel_charge', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Printorders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100, null=True)),
                ('bill_no', models.CharField(max_length=100, null=True)),
                ('bill_date', models.DateField()),
                ('bill_time', models.TimeField(null=True)),
                ('item_code', models.CharField(max_length=100, null=True)),
                ('item_name', models.CharField(max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('gst', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('qty', models.IntegerField()),
                ('tax_amt', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_gst', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('item_cat', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('utype', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('number', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
