# Generated by Django 3.0 on 2024-12-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0002_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
