# Generated by Django 3.0 on 2024-12-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0003_userreg_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(null=True)),
                ('desc', models.CharField(max_length=150, null=True)),
                ('Amount', models.CharField(max_length=150, null=True)),
                ('staffname', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
