# Generated by Django 3.0 on 2024-12-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0004_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.CharField(max_length=50, null=True)),
                ('Item_name', models.CharField(max_length=50, null=True)),
                ('Item_price', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='additem',
            old_name='Item_GST',
            new_name='qty',
        ),
        migrations.RemoveField(
            model_name='additem',
            name='Item_code',
        ),
    ]
