# Generated by Django 3.0 on 2024-12-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0006_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='Item_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='Item_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
