# Generated by Django 3.0 on 2024-12-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0007_auto_20241210_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='Item_price',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='additem',
            name='qty',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Item_price',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='qty',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
