# Generated by Django 3.0 on 2024-12-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0009_billpending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='qty',
            field=models.IntegerField(null=True),
        ),
    ]
