# Generated by Django 3.0 on 2024-12-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0010_auto_20241211_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deletedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('billNo', models.IntegerField(null=True)),
                ('item', models.CharField(max_length=500, null=True)),
                ('qty', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True)),
                ('taxAmt', models.FloatField(null=True)),
            ],
        ),
    ]
