# Generated by Django 3.0 on 2024-12-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0011_deletedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedata',
            name='item_code',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
