# Generated by Django 3.0 on 2024-12-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0013_deletedata_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billpending',
            name='amount',
            field=models.FloatField(max_length=500, null=True),
        ),
    ]
