# Generated by Django 3.0 on 2024-12-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0014_auto_20241211_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='dqty',
            field=models.IntegerField(null=True),
        ),
    ]
